### ISSUE TITLE
Build Appears Broken

### ISSUE THREAD

**Issue by freefal** [veloce/lichobile#809]
From a fresh install of Ubuntu 17.10 I run the following command:

```
==== Ubuntu 17.10 ====
sudo apt-get install nodejs npm git default-jdk chromium-browser
wget https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip
unzip sdk-tools-linux-3859397.zip
wget "https://dl.google.com/android/repository/android-ndk-r16b-linux-x86_64.zip"
unzip android-ndk-r16b-linux-x86_64.zip
gedit ~/.profile
	+ add to bottom "PATH="$HOME/tools:$HOME/android-ndk-r16b:$PATH"
// Log out and log back in
tools/bin/sdkmanager "platform-tools" "platforms;android-23"
sudo npm install -g cordova
git clone https://github.com/veloce/lichobile.git
cd lichobile
npm install
cp env.json.example env.json
vi env.json // :%s/listage.ovh/lichess.org
npm run watch &
chromium-browser --user-data-dir="/tmp/lichobile-chrom" --disable-web-security www/index.html &
cp env.json env-stage.json
cordova platform add android
```

Everything works until that last command where I get the following errors:
```
freefal@freefal-VirtualBox:~/lichobile$ cordova platform add android
? May Cordova anonymously report usage statistics to improve the tool over time? Yes

Thanks for opting into telemetry to help us improve cordova.
Using cordova-fetch for cordova-android@7.0.0
Adding android project...
Creating Cordova project for the Android platform:
    Path: platforms/android
    Package: org.lichess.mobileapp
    Name: lichess
    Activity: MainActivity
    Android target: android-26
Subproject Path: CordovaLib
Subproject Path: app
Android project created with cordova-android@7.0.0
Android Studio project detected
Android Studio project detected
Discovered plugin "com.rjfun.cordova.plugin.lowlatencyaudio" in config.xml. Adding it to the project
Installing "com.rjfun.cordova.plugin.lowlatencyaudio" for android
Adding com.rjfun.cordova.plugin.lowlatencyaudio to package.json
Saved plugin info for "com.rjfun.cordova.plugin.lowlatencyaudio" to config.xml
Discovered plugin "cordova-plugin-app-event" in config.xml. Adding it to the project
Installing "cordova-plugin-app-event" for android
Adding cordova-plugin-app-event to package.json
Saved plugin info for "cordova-plugin-app-event" to config.xml
Discovered plugin "cordova-plugin-appversion" in config.xml. Adding it to the project
Installing "cordova-plugin-appversion" for android
Adding cordova-plugin-appversion to package.json
Saved plugin info for "cordova-plugin-appversion" to config.xml
Discovered plugin "cordova-plugin-crosswalk-webview" in config.xml. Adding it to the project
Installing "cordova-plugin-crosswalk-webview" for android
Subproject Path: CordovaLib
Subproject Path: app

        After much discussion and analysis of the market, we have decided to discontinue support for Android 4.0 (ICS) in Crosswalk starting with version 20.

        So the minSdkVersion of Cordova project is configured to 16 by default.
   
Failed to install 'cordova-plugin-crosswalk-webview': Error: Uncaught, unspecified "error" event. (Parsing /home/freefal/lichobile/platforms/android/res/xml/config.xml failed)
    at EventEmitter.emit (events.js:163:17)
    at EventEmitter.module.exports.emit (/usr/local/lib/node_modules/cordova/node_modules/cordova-common/src/events.js:71:17)
    at Object.ConfigParser (/usr/local/lib/node_modules/cordova/node_modules/cordova-common/src/ConfigParser/ConfigParser.js:34:16)
    at new module.exports (/home/freefal/lichobile/plugins/cordova-plugin-crosswalk-webview/hooks/update_config.js:37:25)
    at module.exports (/home/freefal/lichobile/plugins/cordova-plugin-crosswalk-webview/hooks/after_plugin_install/000-shared_mode_special.js:8:24)
    at runScriptViaModuleLoader (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:188:18)
    at runScript (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:164:16)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:132:20
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/q/q.js:816:30)
Failed to restore plugin "cordova-plugin-crosswalk-webview" from config.xml. You might need to try adding it again. Error: Error: Uncaught, unspecified "error" event. (Parsing /home/freefal/lichobile/platforms/android/res/xml/config.xml failed)
Discovered plugin "cordova-plugin-device" in config.xml. Adding it to the project
Installing "cordova-plugin-device" for android
Adding cordova-plugin-device to package.json
Saved plugin info for "cordova-plugin-device" to config.xml
Discovered plugin "cordova-plugin-dialogs" in config.xml. Adding it to the project
Installing "cordova-plugin-dialogs" for android
Adding cordova-plugin-dialogs to package.json
Saved plugin info for "cordova-plugin-dialogs" to config.xml
Discovered plugin "cordova-plugin-file-transfer" in config.xml. Adding it to the project
Installing "cordova-plugin-file-transfer" for android
Installing "cordova-plugin-file" for android
Installing "cordova-plugin-compat" for android
Plugin doesn't support this project's cordova-android version. cordova-android: 7.0.0, failed version requirement:
      <6.3.0
Skipping 'cordova-plugin-compat' for android

The Android Persistent storage location now defaults to "Internal". Please check this plugin's README to see if your application needs any changes in its config.xml.

If this is a new application no changes are required.

If this is an update to an existing application that did not specify an "AndroidPersistentFileLocation" you may need to add:

      "<preference name="AndroidPersistentFileLocation" value="Compatibility" />"

to config.xml in order for the application to find previously stored files.
       
Adding cordova-plugin-file-transfer to package.json
Saved plugin info for "cordova-plugin-file-transfer" to config.xml
Discovered plugin "cordova-plugin-fullscreen" in config.xml. Adding it to the project
Installing "cordova-plugin-fullscreen" for android
Adding cordova-plugin-fullscreen to package.json
Saved plugin info for "cordova-plugin-fullscreen" to config.xml
Discovered plugin "cordova-plugin-globalization" in config.xml. Adding it to the project
Installing "cordova-plugin-globalization" for android
Adding cordova-plugin-globalization to package.json
Saved plugin info for "cordova-plugin-globalization" to config.xml
Discovered plugin "cordova-plugin-inappbrowser" in config.xml. Adding it to the project
Installing "cordova-plugin-inappbrowser" for android
Adding cordova-plugin-inappbrowser to package.json
Saved plugin info for "cordova-plugin-inappbrowser" to config.xml
Discovered plugin "cordova-plugin-insomnia" in config.xml. Adding it to the project
Installing "cordova-plugin-insomnia" for android
Adding cordova-plugin-insomnia to package.json
Saved plugin info for "cordova-plugin-insomnia" to config.xml
Discovered plugin "cordova-plugin-splashscreen" in config.xml. Adding it to the project
Installing "cordova-plugin-splashscreen" for android
Adding cordova-plugin-splashscreen to package.json
Saved plugin info for "cordova-plugin-splashscreen" to config.xml
Discovered plugin "cordova-plugin-statusbar" in config.xml. Adding it to the project
Installing "cordova-plugin-statusbar" for android
Adding cordova-plugin-statusbar to package.json
Saved plugin info for "cordova-plugin-statusbar" to config.xml
Discovered plugin "cordova-plugin-vibration" in config.xml. Adding it to the project
Installing "cordova-plugin-vibration" for android
Adding cordova-plugin-vibration to package.json
Saved plugin info for "cordova-plugin-vibration" to config.xml
Discovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the project
Installing "cordova-plugin-whitelist" for android

               This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.
         
Adding cordova-plugin-whitelist to package.json
Saved plugin info for "cordova-plugin-whitelist" to config.xml
Discovered plugin "cordova-plugin-x-socialsharing" in config.xml. Adding it to the project
Installing "cordova-plugin-x-socialsharing" for android
Adding cordova-plugin-x-socialsharing to package.json
Saved plugin info for "cordova-plugin-x-socialsharing" to config.xml
Discovered plugin "cordova-plugin-x-toast" in config.xml. Adding it to the project
Installing "cordova-plugin-x-toast" for android
Adding cordova-plugin-x-toast to package.json
Saved plugin info for "cordova-plugin-x-toast" to config.xml
Discovered plugin "cordova-universal-links-plugin" in config.xml. Adding it to the project
Installing "cordova-universal-links-plugin" for android
Installing dependency packages:
{
  "mkpath": ">=1.0.0",
  "node-version-compare": ">=1.0.1",
  "plist": ">=1.2.0",
  "rimraf": ">=2.4",
  "xml2js": ">=0.4"
}
Adding cordova-universal-links-plugin to package.json
Saved plugin info for "cordova-universal-links-plugin" to config.xml
Discovered plugin "de.appplant.cordova.plugin.local-notification" in config.xml. Adding it to the project
Failed to restore plugin "de.appplant.cordova.plugin.local-notification" from config.xml. You might need to try adding it again. Error: Failed to fetch plugin git+https://github.com/katzer/cordova-plugin-local-notifications.git#0.8.5 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module
Discovered plugin "ionic-plugin-keyboard" in config.xml. Adding it to the project
Installing "ionic-plugin-keyboard" for android
Adding ionic-plugin-keyboard to package.json
Saved plugin info for "ionic-plugin-keyboard" to config.xml
Discovered plugin "onesignal-cordova-plugin" in config.xml. Adding it to the project
Installing "onesignal-cordova-plugin" for android
Subproject Path: CordovaLib
Subproject Path: app
Adding onesignal-cordova-plugin to package.json
Saved plugin info for "onesignal-cordova-plugin" to config.xml
Discovered plugin "cordova-plugin-network-information" in config.xml. Adding it to the project
Installing "cordova-plugin-network-information" for android
Adding cordova-plugin-network-information to package.json
Saved plugin info for "cordova-plugin-network-information" to config.xml
Discovered plugin "cordova-plugin-stockfish" in config.xml. Adding it to the project
Installing "cordova-plugin-stockfish" for android
Adding cordova-plugin-stockfish to package.json
Saved plugin info for "cordova-plugin-stockfish" to config.xml
(node:3461) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, open 'platforms/android/AndroidManifest.xml'
done
```

**Comment by veloce** [comment]
@freefal can you try the workaround suggested here?
https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview/issues/188#issuecomment-354438731

If you just want to test the app on your phone, another easy way to fix the build is to remove the `cordova-plugin-crosswalk-webview`.

**Comment by freefal** [comment]
That method didn't work for me, but the combination of the following worked for me:
1) Downgrading `cordova-android` in both `package.json` and `config.xml` to version `6.2.2`
2) Manually installing `zanimo` with `npm install zanimo` - the build complained it wasn't installed even though it's in package.json
3) Accepting that the build was always going to non-fatally fail on trying to fetch `"de.appplant.cordova.plugin.local-notification": "git+https://github.com/katzer/cordova-plugin-local-notifications.git#0.8.5"`, but still ultimately build an APK

**Comment by veloce** [comment]
@freefal https://github.com/veloce/lichobile/commit/63640e70b8eb25c03027732a8fa24ef0ac23fdfb
should solve the zanimo issue.

If you had to downgrade cordova-android because of the crosswalk plugin, the I suggest you to remove the plugin (after removing be sure to search for crosswalk in `platform/android` dir, because cordova may not be able to remove it properly).

**Comment by veloce** [comment]
According to play store stats, android 4.4 is about 7% in version usage distribution. When it reaches 5% we'll remove it, or before if it causes too much trouble.

**Comment by freefal** [comment]
Removing crosswalk webview plugin definitely helped. Do you ever get the error below? I get it every time.
```
Discovered plugin "de.appplant.cordova.plugin.local-notification" in config.xml. Adding it to the project
Failed to restore plugin "de.appplant.cordova.plugin.local-notification" from config.xml. You might need to try adding it again. Error: Failed to fetch plugin git+https://github.com/katzer/cordova-plugin-local-notifications.git#0.8.5 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module
```

**Comment by veloce** [comment]
I think I had this error once, and I solved it somehow, not 100% sure though. You should check their issues, perhaps you could find a workaround here.
